name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.1'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r https://github.com/patcharta/count_stock/blob/main/requirements.txt  # Replace with the correct path to your requirements.txt

    - name: Check if Streamlit is installed
      run: |
        pip list | grep streamlit  # Check if Streamlit is installed
